language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd ./testing
  - pytest
  - coverage run test_image_loader.py

after_success:
  - codecov